In [2]:

import pandas as pd
import numpy as np
from numpy import random
from sklearn.model_selection import train_test_split
import ast
import os
from PIL import Image
import yaml

# 데이터 전처리
- 양품 : 75 * 4 = 300
- 불량품 : 300 * 4 = 1200 랜덤 샘플링

In [3]:
from sklearn.model_selection import train_test_split
import pandas as pd

# CSV 파일 로드 함수
def load_data_with_pandas(file_path):
    data = pd.read_csv(file_path)
    return data

# 데이터 로드
data_bumper = load_data_with_pandas('./data/bumper/bumper_data.csv')
data_door_ed = load_data_with_pandas('./data/door/door_ed_data.csv')
data_door_scratch = load_data_with_pandas('./data/door/door_scratch_data.csv')
data_fender = load_data_with_pandas('./data/fender/fender_ed_data.csv')
data_frame_ed = load_data_with_pandas('./data/frame/frame_ed_data.csv')



# # 0이 처음 출력되는 index 값 추출
first_zero_bumper = data_bumper[data_bumper['quality'] == 0].index[0]

first_zero_door_ed = data_door_ed[data_door_ed['quality'] == 0].index[0]
first_zero_door_scratch = data_door_scratch[data_door_scratch['quality'] == 0].index[0]

first_zero_fender = data_fender[data_fender['quality'] == 0].index[0]

first_zero_frame_ed = data_frame_ed[data_frame_ed['quality'] == 0].index[0]




# 일부 에러 데이터 정규화

In [4]:
# import pandas as pd

# def modify_csv(input_file, output_file, column_name, new_value, first_zero):
#     # CSV 파일 읽기
#     df = pd.read_csv(input_file)

#     # 조건 설정: 첫 번째 0이 나오기 전까지만
#     row_condition = df.index < first_zero_frame_hd

#     # 조건에 해당하는 값 수정
#     df.loc[row_condition, column_name] = new_value

#     # 수정된 데이터 저장
#     df.to_csv(output_file, index=False)

# # 함수 사용 예시
# # modify_csv(
# #     "C:\\Users\\dawoo\\desktop\\sf7\\coding\\pytorch\\project\\data\\data\\output\\frame\\frame_hd_data.csv", 
# #     "./data/data/output/frame/frame_hd_data_modify.csv", 
# #     "bboxes", 
# #     "[]", 
# #     first_zero_frame_hd
# # )

# # modify_csv(
# #     "./data/data/output/frame/frame_sealf_data.csv", 
# #     "./data/data/output/frame/frame_sealf_data_modify.csv", 
# #     "bboxes", 
# #     "[]", 
# #     first_zero_frame_sealf
# # )

# # modify_csv(
# #     "./data/data/output/frame/frame_seamf_data.csv", 
# #     "./data/data/output/frame/frame_seamf_data_modify.csv", 
# #     "bboxes", 
# #     "[]", 
# #     first_zero_frame_seamf
# # )


### index을 통해서 양품과 불량품의 위치를 구분

In [8]:
print(f"bumper 양품 : {len(data_bumper.iloc[:first_zero_bumper])}")
print(f"bumper 불량품 : {len(data_bumper.iloc[first_zero_bumper:])}")

print(f"door_ed 양품 : {len(data_door_ed.iloc[:first_zero_door_ed])}")
print(f"door_ed 불양품 : {len(data_door_ed.iloc[first_zero_door_ed:])}")
print(f"door_scratch 양품 : {len(data_door_scratch.iloc[:first_zero_door_scratch])}")
print(f"door_scratch 불양품 : {len(data_door_scratch.iloc[first_zero_door_scratch:])}")

print(f"data_fender 양품 : {len(data_fender.iloc[:first_zero_fender])}")
print(f"data_fender 불량품 : {len(data_fender.iloc[first_zero_fender:])}")

print(f"data_frame_ed 양품 : {len(data_frame_ed.iloc[:first_zero_frame_ed])}")
print(f"data_frame_ed 불양품 : {len(data_frame_ed.iloc[first_zero_frame_ed:])}")
# print(f"data_frame_hd 양품 : {len(data_frame_hd.iloc[:first_zero_frame_hd])}")
# print(f"data_frame_hd 불양품 : {len(data_frame_hd.iloc[first_zero_frame_hd:])}")
# print(f"data_frame_sealf 양품 : {len(data_frame_sealf.iloc[:first_zero_frame_sealf])}")
# print(f"data_frame_sealf 불양품 : {len(data_frame_sealf.iloc[first_zero_frame_sealf:])}")
# print(f"data_frame_seamf 양품 : {len(data_frame_seamf.iloc[:first_zero_frame_seamf])}")
# print(f"data_frame_seamf 불양품 : {len(data_frame_seamf.iloc[first_zero_frame_seamf:])}")



bumper 양품 : 3472
bumper 불량품 : 9216
door_ed 양품 : 2595
door_ed 불양품 : 2520
door_scratch 양품 : 3463
door_scratch 불양품 : 5015
data_fender 양품 : 3346
data_fender 불량품 : 3282
data_frame_ed 양품 : 2497
data_frame_ed 불양품 : 3443


### 양품 데이터 추출

In [4]:
import pandas as pd

data_ok_bumper = data_bumper.iloc[:first_zero_bumper]
data_door_ed_ok = data_door_ed.iloc[:first_zero_door_ed]
data_door_scratch_ok = data_door_scratch.iloc[:first_zero_door_scratch]
data_ok_fender = data_fender.iloc[:first_zero_fender]
data_ok_frame = data_frame_ed.iloc[:first_zero_frame_ed]
# 범퍼, 도어 스크래치 => 스크래치
# 도어 외장, 휀더, 프레임 => 외장 파손


bumper_ok_random_sample = data_ok_bumper.sample(n=2000, replace=False)
train_bumper_ok, valid_bumper_ok = train_test_split(
    bumper_ok_random_sample, test_size=0.2, stratify=bumper_ok_random_sample['quality'], random_state=60)
train_bumper_ok_80, test_bumper_ok = train_test_split(
    train_bumper_ok, test_size=0.2, stratify=train_bumper_ok['quality'], random_state=60)

# fender_ok_random_sample = data_ok_fender.sample(n=300, replace=False)
# train_fender_ok, valid_fender_ok = train_test_split(
#     fender_ok_random_sample, test_size=0.2, stratify=fender_ok_random_sample['quality'], random_state=60)
# train_fender_ok_80, test_fender_ok = train_test_split(
#     train_fender_ok, test_size=0.2, stratify=train_fender_ok['quality'], random_state=60)

# door_ed_ok_random_sample = data_door_ed_ok.sample(n=300, replace=False)
# train_door_ed_ok, valid_door_ed_ok = train_test_split(
#     door_ed_ok_random_sample, test_size=0.2, stratify=door_ed_ok_random_sample['quality'], random_state=60)
# train_door_ed_ok_80, test_door_ed_ok = train_test_split(
#     train_door_ed_ok, test_size=0.2, stratify=train_door_ed_ok['quality'], random_state=60)

door_scratch_ok_random_sample = data_door_scratch_ok.sample(
    n=2000, replace=False)
train_door_scratch_ok, valid_door_scratch_ok = train_test_split(
    door_scratch_ok_random_sample, test_size=0.2, stratify=door_scratch_ok_random_sample['quality'], random_state=60)
train_door_scratch_ok_80, test_door_scratch_ok = train_test_split(
    train_door_scratch_ok, test_size=0.2, stratify=train_door_scratch_ok['quality'], random_state=60)

# frame_ok_random_sample = data_ok_frame.sample(n=300, replace=False)
# train_frame_ok, valid_frame_ok = train_test_split(
#     frame_ok_random_sample, test_size=0.2, stratify=frame_ok_random_sample['quality'], random_state=60)
# train_frame_ok_80, test_frame_ok = train_test_split(
#     train_frame_ok, test_size=0.2, stratify=train_frame_ok['quality'], random_state=60)


ok_train_data = pd.concat([train_bumper_ok_80,
                          train_door_scratch_ok_80], ignore_index=True, axis=0)

ok_valid_data = pd.concat([valid_bumper_ok,
                          valid_door_scratch_ok], ignore_index=True, axis=0)
ok_test_data = pd.concat([test_bumper_ok,
                         test_door_scratch_ok], ignore_index=True, axis=0)

print(len(ok_train_data))
print(len(ok_valid_data))
print(len(ok_test_data))
# ok_data

2560
800
640


### 불량품 데이터 추출

In [5]:
import pandas as pd
data_fault_bumper = data_bumper.iloc[first_zero_bumper:]
data_door_ed_fault = data_door_ed.iloc[first_zero_door_ed:]
data_door_scratch_fault = data_door_scratch.iloc[first_zero_door_scratch:]
data_fault_fender = data_fender.iloc[first_zero_fender:]
data_fault_frame = data_frame_ed.iloc[first_zero_frame_ed:]
# 범퍼, 도어 스크래치 => 스크래치
# 도어 외장, 휀더, 프레임 => 외장 파손


# 300개를 무작위로 추출 (복원 추출, random_state 설정)
bumper_fault_random_sample = data_fault_bumper.sample(n=2000, replace=False)
train_bumper_fault, valid_bumper_fault = train_test_split(
    bumper_fault_random_sample, test_size=0.2, stratify=bumper_fault_random_sample['quality'], random_state=60)
train_bumper_fault_80, test_bumper_fault = train_test_split(
    train_bumper_fault, test_size=0.2, stratify=train_bumper_fault['quality'], random_state=60)

# fender_fault_random_sample = data_fault_fender.sample(n=300, replace=False)
# train_fender_fault, valid_fender_fault = train_test_split(
#     fender_fault_random_sample, test_size=0.2, stratify=fender_fault_random_sample['quality'], random_state=60)
# train_fender_fault_80, test_fender_fault = train_test_split(
#     train_fender_fault, test_size=0.2, stratify=train_fender_fault['quality'], random_state=60)

# door_ed_fault_random_sample = data_door_ed_fault.sample(n=300, replace=False)
# train_door_ed_fault, valid_door_ed_fault = train_test_split(
#     door_ed_fault_random_sample, test_size=0.2, stratify=door_ed_fault_random_sample['quality'], random_state=60)
# train_door_ed_fault_80, test_door_ed_fault = train_test_split(
#     train_door_ed_fault, test_size=0.2, stratify=train_door_ed_fault['quality'], random_state=60)

door_scratch_fault_random_sample = data_door_scratch_fault.sample(
    n=2000, replace=False)
train_door_scratch_fault, valid_door_scratch_fault = train_test_split(
    door_scratch_fault_random_sample, test_size=0.2, stratify=door_scratch_fault_random_sample['quality'], random_state=60)
train_door_scratch_fault_80, test_door_scratch_fault = train_test_split(
    train_door_scratch_fault, test_size=0.2, stratify=train_door_scratch_fault['quality'], random_state=60)

# frame_fault_random_sample = data_fault_frame.sample(n=300, replace=False)
# train_frame_fault, valid_frame_fault = train_test_split(
#     frame_fault_random_sample, test_size=0.2, stratify=frame_fault_random_sample['quality'], random_state=60)
# train_frame_fault_80, test_frame_fault = train_test_split(
#     train_frame_fault, test_size=0.2, stratify=train_frame_fault['quality'], random_state=60)

# 결과 출력
# print(valid_bumper_fault)
# print(len(valid_bumper_fault))

# print(valid_fender_fault)
# print(len(valid_fender_fault))

# print(valid_door_ed_fault)
# print(len(valid_door_ed_fault))

# print(valid_door_scratch_fault)
# print(len(valid_door_scratch_fault))

# print(valid_frame_fault)
# print(len(valid_frame_fault))

fault_train_data = pd.concat([train_bumper_fault_80,
                              train_door_scratch_fault_80], ignore_index=True, axis=0)

fault_valid_data = pd.concat([valid_bumper_fault,
                              valid_door_scratch_fault], ignore_index=True, axis=0)
fault_test_data = pd.concat([test_bumper_fault,
                             test_door_scratch_fault], ignore_index=True, axis=0)

print(len(fault_train_data))
print(len(fault_valid_data))
print(len(fault_test_data))

# fault_data

2560
800
640


# 테스트 데이터

### bboxes 데이터 추출

In [11]:
import ast

def parse_bboxes(data):
    """
    문자열 형태의 bounding box 정보를 파싱하여 리스트 형태로 변환하는 함수

    Args:
        data: 파싱할 데이터셋

    Returns:
        list: 파싱된 bounding box 리스트
    """

    bboxes_list = []
    for bbox_str in data["bboxes"]:
        try:
            bboxes = ast.literal_eval(bbox_str)
            bbox_list = []
            for bbox in bboxes:
                x, y, w, h = bbox
                bbox_list.append([x, y, w, h])
            bboxes_list.append(bbox_list)
        except (ValueError, SyntaxError) as e:
            print(f"Error parsing bbox: {e}")
    return bboxes_list

# 데이터셋별 bounding box 파싱
train_ok_bboxes = parse_bboxes(ok_train_data)
valid_ok_bboxes = parse_bboxes(ok_valid_data)
test_ok_bboxes = parse_bboxes(ok_test_data)
train_fault_bboxes = parse_bboxes(fault_train_data)
valid_fault_bboxes = parse_bboxes(fault_valid_data)
test_fault_bboxes = parse_bboxes(fault_test_data)

# 결과 출력 (예시)
# print(train_ok_bboxes[:5])
# print(valid_ok_bboxes[:5])
# print(test_ok_bboxes[:5])
# print(train_fault_bboxes[:5])
# print(valid_fault_bboxes[:5])
# print(test_fault_bboxes[:5])

# .yaml label 데이터 생성

### 1. 디렉토리 경로 전처리

In [12]:
import os
from PIL import Image


def extract_image_info(image_paths):
    """
    이미지 경로 리스트에서 이미지 크기, 디렉토리 경로, 파일 이름을 추출하는 함수

    Args:
        image_paths (list): 이미지 경로 리스트

    Returns:
        tuple: (image_sizes, image_dirs, file_names)
            image_sizes (list): 이미지 크기 리스트
            image_dirs (list): 이미지 디렉토리 경로 리스트
            file_names (list): 이미지 파일 이름 리스트
    """

    image_sizes = []
    image_dirs = []
    file_names = []

    for path in image_paths:
        try:
            image = Image.open(path)
            width, height = image.size
            image_sizes.append((width, height))
            image_dirs.append(os.path.dirname(path) + os.sep)
            file_names.append(os.path.splitext(os.path.basename(path))[0])
        except FileNotFoundError:
            print(f"파일을 찾을 수 없습니다: {path}")

    return image_sizes, image_dirs, file_names

# 데이터 준비 (예시)
train_ok_image_paths = ok_train_data.iloc[:, 0].tolist()
valid_ok_image_paths = ok_valid_data.iloc[:, 0].tolist()
test_ok_image_paths = ok_test_data.iloc[:, 0].tolist()
train_fault_image_paths = fault_train_data.iloc[:, 0].tolist()
valid_fault_image_paths = fault_valid_data.iloc[:, 0].tolist()
test_fault_image_paths = fault_test_data.iloc[:, 0].tolist()

# 이미지 정보 추출
train_sizes_ok, train_dirs_ok, train_names_ok = extract_image_info(train_ok_image_paths)
valid_sizes_ok, valid_dirs_ok, valid_names_ok = extract_image_info(valid_ok_image_paths)
test_sizes_ok, test_dirs_ok, test_names_ok = extract_image_info(test_ok_image_paths)
train_sizes_fault, train_dirs_fault, train_names_fault = extract_image_info(train_fault_image_paths)
valid_sizes_fault, valid_dirs_fault, valid_names_fault = extract_image_info(valid_fault_image_paths)
test_sizes_fault, test_dirs_fault, test_names_fault = extract_image_info(test_fault_image_paths)

# 결과 출력 ok
# print("train_sizes_ok 이미지 크기:", train_sizes_ok[:5])
# print("train_dirs_ok 이미지 디렉토리:", train_dirs_ok[:5])
# print("train_names_ok 파일 이름:", train_names_ok[:5])
# print()
# print("valid_sizes_ok 이미지 크기:", valid_sizes_ok[:5])
# print("valid_dirs_ok 이미지 디렉토리:", valid_dirs_ok[:5])
# print("valid_names_ok 파일 이름:", valid_names_ok[:5])
# print()
# print("test_sizes_ok 이미지 크기:", test_sizes_ok[:5])
# print("test_dirs_ok 이미지 디렉토리:", test_dirs_ok[:5])
# print("test_names_ok 파일 이름:", test_names_ok[:5])
# 결과 출력 fault
# print("train_sizes_fault 이미지 크기:", train_sizes_fault[:5])
# print("train_dirs_fault 이미지 디렉토리:", train_dirs_fault[:5])
# print("train_names_fault 파일 이름:", train_names_fault[:5])
# print()
# print("valid_sizes_fault 이미지 크기:", valid_sizes_fault[:5])
# print("valid_dirs_fault 이미지 디렉토리:", valid_dirs_fault[:5])
# print("valid_names_fault 파일 이름:", valid_names_fault[:5])
# print()
# print("test_sizes_fault 이미지 크기:", test_sizes_fault[:5])
# print("test_dirs_fault 이미지 디렉토리:", test_dirs_fault[:5])
# print("test_names_fault 파일 이름:", test_names_fault[:5])

c:\Users\dawoo\Desktop\SF7\coding\PYTORCH\pytorch-env\Lib\site-packages\PIL\Image.py:3186: DecompressionBombWarning: Image size (108000000 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(


### 3. 부품 상태 전처리

In [17]:
# 부품 상태를 체크하는 함수
def get_label(part, status, weight):
    if part == "범퍼":
         if status == 1:
            return 0
         else:
            return 1
    elif part == "도어":
         if status == 1:
            return 0
         else:
             return 2



# 예시 부품과 상태
parts_and_status_train_ok = []
parts_and_status_valid_ok = []
parts_and_status_test_ok = []
for quality, part, weight in zip(ok_train_data.iloc[:, 1], ok_train_data.iloc[:, 2], ok_train_data.iloc[:, 4]):
    parts_and_status_train_ok.append(
        {"part": part, "status": quality, "weight": weight})

for quality, part, weight in zip(ok_test_data.iloc[:, 1], ok_test_data.iloc[:, 2], ok_test_data.iloc[:, 4]):
    parts_and_status_test_ok.append(
        {"part": part, "status": quality, "weight": weight})

for quality, part, weight in zip(ok_valid_data.iloc[:, 1], ok_valid_data.iloc[:, 2], ok_valid_data.iloc[:, 4]):
    parts_and_status_valid_ok.append(
        {"part": part, "status": quality, "weight": weight})


parts_and_status_train_fault = []
parts_and_status_valid_fault = []
parts_and_status_test_fault = []
for quality, part, weight in zip(fault_train_data.iloc[:, 1], fault_train_data.iloc[:, 2], fault_train_data.iloc[:, 4]):
    parts_and_status_train_fault.append(
        {"part": part, "status": quality, "weight": weight})

for quality, part, weight in zip(fault_test_data.iloc[:, 1], fault_test_data.iloc[:, 2], fault_test_data.iloc[:, 4]):
    parts_and_status_test_fault.append(
        {"part": part, "status": quality, "weight": weight})

for quality, part, weight in zip(fault_valid_data.iloc[:, 1], fault_valid_data.iloc[:, 2], fault_valid_data.iloc[:, 4]):
    parts_and_status_valid_fault.append(
        {"part": part, "status": quality, "weight": weight})

# print(f"parts_and_status_train : {parts_and_status_train_ok}")
print(f"parts_and_status_test_ok : {parts_and_status_test_ok}")
# print(f"parts_and_status_valid : {parts_and_status_valid_ok}")

# print(f"parts_and_status_train : {parts_and_status_train_fault}")
print(f"parts_and_status_test_fault : {parts_and_status_test_fault}")
# print(f"parts_and_status_valid : {parts_and_status_valid_fault}")

# 라벨링 결과를 저장할 리스트
labels_train_ok = []
labels_valid_ok = []
label_test_ok = []

# 각 부품 상태에 대해 라벨을 설정
for item in parts_and_status_train_ok:
    label = get_label(item["part"], item["status"], item["weight"])
    labels_train_ok.append(label)
for item in parts_and_status_test_ok:
    label = get_label(item["part"], item["status"], item["weight"])
    label_test_ok.append(label)
for item in parts_and_status_valid_ok:
    label = get_label(item["part"], item["status"], item["weight"])
    labels_valid_ok.append(label)

# # 결과 출력
# print("labels_train_ok 라벨링 결과 :", labels_train_ok)
# print("labels_valid_ok 라벨링 결과 :", labels_valid_ok)
print("label_test_ok 라벨링 결과 :", label_test_ok)

# 라벨링 결과를 저장할 리스트
labels_train_fault = []
labels_valid_fault = []
label_test_fault = []

# 각 부품 상태에 대해 라벨을 설정
for item in parts_and_status_train_fault:
    label = get_label(item["part"], item["status"], item["weight"])
    labels_train_fault.append(label)
for item in parts_and_status_test_fault:
    label = get_label(item["part"], item["status"], item["weight"])
    label_test_fault.append(label)
for item in parts_and_status_valid_fault:
    label = get_label(item["part"], item["status"], item["weight"])
    labels_valid_fault.append(label)

# # 결과 출력
# print("labels_train_fault 라벨링 결과 :", labels_train_fault)
# print("labels_valid_fault 라벨링 결과 :", labels_valid_fault)
print("label_test_fualt 라벨링 결과 :", label_test_fault)

parts_and_status_test_ok : [{'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'part': '범퍼', 'status': 1, 'weight': 0.4}, {'pa

In [8]:
import os
import shutil

# 폴더 초기화 함수
def prepare_output_dir(output_dir):
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)  # 기존 폴더 삭제
    os.makedirs(output_dir, exist_ok=True)  # 새 폴더 생성

# 이미지 복사 함수
def copy_images(output_dir, data):
    image_dir = os.path.join(output_dir, 'images')
    
    # 이미지 폴더가 존재하는지 확인하고, 없으면 새로 생성
    if not os.path.exists(image_dir):
        os.makedirs(image_dir)

    for index, row in data.iterrows():
        image_path = row['path']
        if os.path.exists(image_path):  # 이미지 경로 확인
            shutil.copy(image_path, image_dir)
        else:
            print(f"[WARNING] Image not found: {image_path}")

# YOLO 형식 변환 함수
def convert_to_yolo_format(bbox, label, image_width, image_height):
    yolo_labels = []

    if not bbox or len(bbox) == 0:  # 바운딩 박스가 없을 경우
        yolo_labels.append(f"{label} 0.0 0.0 0.0 0.0")
    else:
        for x_min, y_min, width, height in bbox:
            x_center = (x_min + width / 2) / image_width
            y_center = (y_min + height / 2) / image_height
            norm_width = width / image_width
            norm_height = height / image_height
            yolo_labels.append(f"{label} {x_center:.6f} {y_center:.6f} {norm_width:.6f} {norm_height:.6f}")

    return yolo_labels

# YOLO 라벨 저장 함수
def save_yolo_labels(output_dir, bboxes, labels, size, names):
    label_dir = os.path.join(output_dir, 'labels')

    # 라벨 폴더가 존재하는지 확인하고, 없으면 새로 생성
    if not os.path.exists(label_dir):
        os.makedirs(label_dir)

    for bbox, label, (w, h), name in zip(bboxes, labels, size, names):
        yolo_labels = convert_to_yolo_format(bbox, label, w, h)

        txt_file_path = os.path.join(label_dir, f"{name}.txt")
        with open(txt_file_path, 'w') as txt_file:
            for yolo_data in yolo_labels:
                txt_file.write(f"{yolo_data}\n")

        # 디버깅 로그 추가
        print(f"[INFO] Saved YOLO label: {txt_file_path} (bbox count: {len(bbox)})")

# 이미지 복사 및 라벨 저장 작업을 한 번만 처리하도록 수정
def process_data(output_dir, data, bboxes, labels, sizes, names):
    
    copy_images(output_dir, data)  # 이미지 복사
    save_yolo_labels(output_dir, bboxes, labels, sizes, names)  # YOLO 라벨 저장

# 디렉토리 설정
train_output_dir = '.\\train'
valid_output_dir = '.\\valid'
test_output_dir = '.\\test'
prepare_output_dir(train_output_dir)
prepare_output_dir(valid_output_dir)
prepare_output_dir(test_output_dir)

# 이미지 및 라벨 처리
process_data(train_output_dir, ok_train_data, train_ok_bboxes, labels_train_ok, train_sizes_ok, train_names_ok)
process_data(test_output_dir, ok_test_data, test_ok_bboxes, label_test_ok, test_sizes_ok, test_names_ok)
process_data(valid_output_dir, ok_valid_data, valid_ok_bboxes, labels_valid_ok, valid_sizes_ok, valid_names_ok)

process_data(train_output_dir, fault_train_data, train_fault_bboxes, labels_train_fault, train_sizes_fault, train_names_fault)
process_data(test_output_dir, fault_test_data, test_fault_bboxes, label_test_fault, test_sizes_fault, test_names_fault)
process_data(valid_output_dir, fault_valid_data, valid_fault_bboxes, labels_valid_fault, valid_sizes_fault, valid_names_fault)


[INFO] Saved YOLO label: .\train\labels\205_101_10_80f53a52-a76b-47e2-b771-e0dcb140d424.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_dc986b69-c17e-4a86-99e8-00922ad7f4a4.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_0bc8b59d-b2fe-4720-932e-d2299d52f031.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_96e1f001-7112-4bd3-b3dc-9a2b083c32b6.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_292d4e10-1d43-44e2-ade6-c8d78ff6c6a3.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_1b31606d-f13e-404d-a63d-150a058bc66e.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_ecbe2c0b-fba3-4733-bb42-e69aa4f94cc1.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_d38d7d50-0c1b-4494-941b-f511c0c2b6c7.txt (bbox count: 0)
[INFO] Saved YOLO label: .\train\labels\205_101_10_03b96b80-6043-490a-a927-523a3c541b87.txt (bbox count: 0)
[INFO] Saved YOLO label: .\t

## 모델 코드 작성

In [11]:
import yaml
from ultralytics import YOLO

# 가중치를 계산하기 위한 thresholds
thresholds = {
    0: 0.75,
    1: 0.4,
    2: 0.35,
}

# 클래스별 가중치 계산
class_weights = {cls: round(1 / threshold, 2)
                 for cls, threshold in thresholds.items()}
print("Class Weights:", class_weights)

# YAML 파일에 저장할 데이터
yaml_data = {
    "train": "C:/Users/dawoo/Desktop/sf7/coding/pytorch/multi_scratch//train/images",
    "val": "C:/Users/dawoo/Desktop/sf7/coding/pytorch/multi_scratch/valid/images",
    "test": "C:/Users/dawoo/Desktop/sf7/coding/pytorch/multi_scratch/test/images",
    "nc": len(class_weights),  # 클래스 수
    "names": ["ok", "fault_1", "fault_2"],  # 클래스 이름
    "class_weights": class_weights,  # 클래스별 가중치 추가
    "augment": {
        "mosaic": 0.4,  # 모자이크 비율 강화
        "random_shadow": 0.3,  # 그림자 효과로 대비를 강화
        "brightness": 0.4,  # 밝기 변화를 강화
        "contrast": 0.5,  # 대비 변화를 강화
        "sharpen": 0.35,  # 선명도 조정으로 디테일 강조
        "gauss_noise": 0.3,  # 노이즈 추가로 데이터 다양성 증가
        "hsv_h": 0.4,  # 색조 변화로 흰색 차량의 색상 다양화
        "hsv_s": 0.4,  # 채도 변화
        "hsv_v": 0.4,  # 명도 변화
    }

}

# YAML 파일 생성
yaml_path = "edit2.yaml"
with open(yaml_path, "w") as yaml_file:
    yaml.dump(yaml_data, yaml_file, default_flow_style=False, sort_keys=False)

print(f"YAML 파일이 성공적으로 생성되었습니다: {yaml_path}")

Class Weights: {0: 1.33, 1: 2.5, 2: 2.86}
YAML 파일이 성공적으로 생성되었습니다: edit2.yaml


In [ ]:
from ultralytics import YOLO

# 모델 로드
model = YOLO("yolov8s.pt")

# 학습 설정
model.train(
    data="edit2.yaml",
    epochs=60,
    batch=16,
    imgsz=640,
    device="cuda",
    half=True,  # FP16 연산으로 메모리 절약
    workers=4,
    project="scratch_detect",
    name="model_8_s_60_16_5120_test1",
    lr0=0.0001,
    lrf=0.15,
    momentum=0.937,
    conf=0.3,    # Confidence threshold
    weight_decay=0.0001,
    warmup_epochs=5,
    cos_lr=True,
    patience=5,
    cache=True,
    augment=True,
    optimizer="Adamw",
)

# 학습 완료 후 모델 저장
model_path = "model_8_s_60_16_5120_test1.pt"
model.save(model_path)
print(f"모델이 성공적으로 저장되었습니다: {model_path}")

New https://pypi.org/project/ultralytics/8.3.68 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.67  Python-3.12.0 torch-2.5.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolov8s.pt, data=edit2.yaml, epochs=60, time=None, patience=5, batch=16, imgsz=640, save=True, save_period=-1, cache=True, device=cuda, workers=4, project=scratch_detect, name=model_8_s_60_16_5120_test12, exist_ok=False, pretrained=True, optimizer=Adamw, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=0.3, iou=0.7, max_det=300, half=True, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=True, agnostic_nms=False, classes=None, retina_masks=False, embe

train: Scanning C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\labels.cache... 5120 images, 0 backgrounds, 9 corrupt: 100%|██████████| 5120/5120 [00:00<?, ?it/s]

train: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\images\204_101_10_00737753-35cf-4992-8245-310298e8ceb1.jpg: corrupt JPEG restored and saved
train: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\images\204_101_10_00b980e4-f641-4427-a139-09886c9f36b4.jpg: corrupt JPEG restored and saved
train: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\images\204_101_10_00bb841d-06ad-4cc7-ac02-101f4d8a844d.jpg: corrupt JPEG restored and saved
train: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\images\204_101_10_00ed2af6-13eb-47f2-9a76-e82cd99a6a59.jpg: corrupt JPEG restored and saved
train: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\images\204_101_10_01612304-837e-4976-8370-354f9e3aff10.jpg: corrupt JPEG restored and saved
train: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\train\images\204_101_10_01688074-54a8-427e-9169-fe958747e02e.jpg: corrupt JPEG

WARNING  cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.


train: Caching images (3.4GB RAM): 100%|██████████| 5111/5111 [01:24<00:00, 60.21it/s]
val: Scanning C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\labels.cache... 1600 images, 0 backgrounds, 2 corrupt: 100%|██████████| 1600/1600 [00:00<?, ?it/s]

val: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\images\204_101_10_00306a3c-2548-4830-a141-3c60a3905a8a.jpg: corrupt JPEG restored and saved
val: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\images\204_101_10_0077e6a3-9361-4970-845b-6e954527c857.jpg: corrupt JPEG restored and saved
val: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\images\204_101_10_02b4a781-e6e1-4e6b-b45f-1845b66f9dce.jpg: corrupt JPEG restored and saved
val: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\images\204_101_10_04a49022-581d-44bc-897c-1661834aebb4.jpg: corrupt JPEG restored and saved
val: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\images\204_101_10_04cc9ef4-baa5-429a-984d-85d4393e3cfe.jpg: corrupt JPEG restored and saved
val: WARNING  C:\Users\dawoo\Desktop\SF7\coding\PYTORCH\multi_scratch\valid\images\204_101_10_06b93ee5-707e-4496-9a1d-84be8efaeeae.jpg: corrupt JPEG restored an

WARNING  cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.


val: Caching images (1.0GB RAM): 100%|██████████| 1598/1598 [00:26<00:00, 59.98it/s]


Plotting labels to scratch_detect\model_8_s_60_16_5120_test12\labels.jpg... 
optimizer: AdamW(lr=0.0001, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0001), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to scratch_detect\model_8_s_60_16_5120_test12
Starting training for 60 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/60         4G      1.524      1.704      1.327         14        640: 100%|██████████| 320/320 [02:08<00:00,  2.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:29<00:00,  1.72it/s]

                   all       1598       2164      0.391       0.19      0.282      0.164



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/60      3.79G      1.225       1.07      1.132         24        640: 100%|██████████| 320/320 [02:01<00:00,  2.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:55<00:00,  1.10s/it]

                   all       1598       2164      0.374      0.265      0.306      0.175



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/60      3.78G      1.063     0.8928       1.07         19        640: 100%|██████████| 320/320 [02:00<00:00,  2.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:27<00:00,  1.79it/s]

                   all       1598       2164      0.381      0.263      0.312      0.198



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/60       3.9G     0.9468     0.7754      1.022         24        640: 100%|██████████| 320/320 [01:59<00:00,  2.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:35<00:00,  1.91s/it]

                   all       1598       2164      0.374      0.357      0.368      0.216



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/60      3.78G     0.8884      0.718     0.9975         26        640: 100%|██████████| 320/320 [01:59<00:00,  2.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:28<00:00,  1.77it/s]

                   all       1598       2164      0.414      0.348      0.388      0.228



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/60      3.92G     0.8189     0.6639     0.9763         15        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:10<00:00,  1.41s/it]

                   all       1598       2164      0.384      0.343      0.358      0.211



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/60      3.89G     0.7853     0.6316     0.9688         21        640: 100%|██████████| 320/320 [01:59<00:00,  2.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:31<00:00,  1.56it/s]

                   all       1598       2164      0.372      0.359      0.367      0.219



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/60      3.76G      0.741     0.5992     0.9536         21        640: 100%|██████████| 320/320 [01:58<00:00,  2.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:49<00:00,  1.02it/s]

                   all       1598       2164       0.39      0.367      0.386      0.231



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/60      3.89G     0.7154     0.5777     0.9426         20        640: 100%|██████████| 320/320 [01:59<00:00,  2.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:33<00:00,  1.50it/s]

                   all       1598       2164      0.395       0.37      0.397      0.243



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/60      4.07G     0.6895     0.5481     0.9346         23        640: 100%|██████████| 320/320 [03:28<00:00,  1.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:16<00:00,  1.53s/it]

                   all       1598       2164      0.393       0.36      0.377      0.227



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/60      4.07G     0.6689     0.5341      0.928         26        640: 100%|██████████| 320/320 [03:43<00:00,  1.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:41<00:00,  1.21it/s]

                   all       1598       2164      0.399      0.366      0.396       0.24



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/60      3.91G     0.6555     0.5203     0.9238         23        640: 100%|██████████| 320/320 [02:06<00:00,  2.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:11<00:00,  1.42s/it]

                   all       1598       2164      0.394       0.39      0.405      0.247



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/60      4.07G     0.6378     0.5043     0.9163         24        640: 100%|██████████| 320/320 [03:14<00:00,  1.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:10<00:00,  1.42s/it]

                   all       1598       2164      0.393      0.388      0.404      0.253



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/60      3.91G      0.612     0.4818     0.9143         19        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:49<00:00,  1.01it/s]

                   all       1598       2164      0.416      0.375      0.402      0.247



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/60      4.07G      0.602     0.4779      0.907         21        640: 100%|██████████| 320/320 [03:22<00:00,  1.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:11<00:00,  1.43s/it]

                   all       1598       2164      0.398      0.394      0.405      0.253



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/60      3.91G     0.5962     0.4774     0.9088         26        640: 100%|██████████| 320/320 [01:58<00:00,  2.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:35<00:00,  1.42it/s]

                   all       1598       2164      0.376      0.396      0.398      0.246



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/60      4.08G     0.5814     0.4585     0.9002         13        640: 100%|██████████| 320/320 [03:23<00:00,  1.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:29<00:00,  1.69it/s]

                   all       1598       2164        0.4      0.372      0.398      0.238



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/60      4.05G     0.5702     0.4481     0.8983         22        640: 100%|██████████| 320/320 [03:13<00:00,  1.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:33<00:00,  1.49it/s]

                   all       1598       2164       0.42      0.374      0.411      0.253



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/60      4.05G     0.5558     0.4394     0.8932         25        640: 100%|██████████| 320/320 [03:14<00:00,  1.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:30<00:00,  1.65it/s]

                   all       1598       2164      0.424      0.376      0.405      0.248



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/60      4.07G     0.5567     0.4389     0.8965         25        640: 100%|██████████| 320/320 [03:25<00:00,  1.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:33<00:00,  1.47it/s]

                   all       1598       2164      0.388      0.411      0.414      0.255



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/60      4.07G     0.5424     0.4246     0.8893         20        640: 100%|██████████| 320/320 [03:16<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:30<00:00,  1.65it/s]

                   all       1598       2164      0.385      0.398      0.404       0.25



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/60      4.07G     0.5368     0.4238     0.8886         23        640: 100%|██████████| 320/320 [03:18<00:00,  1.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:31<00:00,  1.61it/s]

                   all       1598       2164      0.401      0.387      0.408      0.253



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/60      4.07G     0.5372     0.4226     0.8894         26        640: 100%|██████████| 320/320 [03:10<00:00,  1.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:10<00:00,  1.42s/it]

                   all       1598       2164      0.411      0.394      0.413      0.258



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/60      3.91G     0.5233     0.4111     0.8843         32        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:37<00:00,  1.94s/it]

                   all       1598       2164      0.413      0.377      0.402      0.247



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/60      3.89G     0.5106     0.4082     0.8831         15        640: 100%|██████████| 320/320 [01:58<00:00,  2.69it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:32<00:00,  1.56it/s]

                   all       1598       2164      0.446      0.379      0.421      0.265



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/60      3.91G     0.5069     0.3998      0.882         26        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:36<00:00,  1.93s/it]

                   all       1598       2164      0.415      0.404       0.42      0.264



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/60      3.91G     0.4987     0.3921     0.8788         19        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:31<00:00,  1.57it/s]

                   all       1598       2164      0.384      0.416      0.404      0.246



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/60      3.91G     0.4898      0.389     0.8775         26        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:38<00:00,  1.96s/it]

                   all       1598       2164       0.43      0.398      0.429      0.267



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/60      3.91G     0.4909     0.3842     0.8778         24        640: 100%|██████████| 320/320 [01:58<00:00,  2.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:38<00:00,  1.29it/s]

                   all       1598       2164      0.446      0.394      0.436      0.275



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/60      3.92G     0.4827      0.375     0.8737         21        640: 100%|██████████| 320/320 [02:06<00:00,  2.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:15<00:00,  1.51s/it]

                   all       1598       2164      0.423      0.403      0.422      0.263



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/60      4.05G     0.4809     0.3817     0.8747         32        640: 100%|██████████| 320/320 [03:31<00:00,  1.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:39<00:00,  1.27it/s]

                   all       1598       2164      0.433      0.407      0.438      0.274



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/60      3.91G     0.4709     0.3688     0.8716         29        640: 100%|██████████| 320/320 [02:06<00:00,  2.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:15<00:00,  1.50s/it]

                   all       1598       2164      0.406      0.415      0.424      0.262



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/60      4.05G     0.4614     0.3662     0.8701         15        640: 100%|██████████| 320/320 [03:28<00:00,  1.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:40<00:00,  1.23it/s]

                   all       1598       2164       0.43      0.432      0.446      0.283



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/60      3.89G       0.45     0.3562     0.8654         23        640: 100%|██████████| 320/320 [02:07<00:00,  2.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:03<00:00,  1.28s/it]

                   all       1598       2164      0.423      0.411      0.436      0.274



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/60      4.07G     0.4508     0.3589      0.866         28        640: 100%|██████████| 320/320 [03:23<00:00,  1.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:34<00:00,  1.88s/it]

                   all       1598       2164      0.419      0.399      0.427      0.267



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/60      3.89G     0.4494     0.3516     0.8668         19        640: 100%|██████████| 320/320 [02:07<00:00,  2.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:39<00:00,  1.27it/s]

                   all       1598       2164      0.413      0.403      0.418      0.263



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/60      4.07G     0.4417     0.3486     0.8661         10        640: 100%|██████████| 320/320 [03:13<00:00,  1.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:33<00:00,  1.88s/it]

                   all       1598       2164      0.425      0.414       0.43      0.273



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/60      3.91G     0.4424     0.3498      0.866         19        640: 100%|██████████| 320/320 [02:07<00:00,  2.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [01:10<00:00,  1.41s/it]

                   all       1598       2164      0.442       0.41      0.443      0.282


EarlyStopping: Training stopped early as no improvement observed in last 5 epochs. Best results observed at epoch 33, best model saved as best.pt.
To update EarlyStopping(patience=5) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

38 epochs completed in 2.239 hours.
Optimizer stripped from scratch_detect\model_8_s_60_16_5120_test12\weights\last.pt, 22.5MB
Optimizer stripped from scratch_detect\model_8_s_60_16_5120_test12\weights\best.pt, 22.5MB

Validating scratch_detect\model_8_s_60_16_5120_test12\weights\best.pt...
Ultralytics 8.3.67  Python-3.12.0 torch-2.5.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)
Model summary (fused): 168 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 50/50 [00:25<00:00,  1.95it/s]


                   all       1598       2164      0.462      0.399      0.445      0.289
                    ok        800        800          0          0          0          0
               fault_1        400        728      0.644      0.564      0.613      0.379
               fault_2        398        636      0.742      0.632      0.722      0.487
Speed: 0.4ms preprocess, 10.7ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to scratch_detect\model_8_s_60_16_5120_test12
모델이 성공적으로 저장되었습니다: model_8_s_60_16_5120_test1.pt


In [1]:
from ultralytics import YOLO
# 모델 로드 및 추론
model = YOLO("C:\\Users\\dawoo\\desktop\\sf7\\coding\\pytorch\\multi_scratch\\model_8_s_60_16_5120_test.pt").to("cuda")
results = model.predict(source="C:\\Users\\dawoo\\desktop\\sf7\\coding\\pytorch\\multi_scratch\\test\\images", save=True, imgsz=640)



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

image 1/1280 C:\Users\dawoo\desktop\sf7\coding\pytorch\multi_scratch\test\images\204_101_10_0045acc2-14c7-457a-98db-eacc6ddf09aa.jpg: 320x640 (no detections), 73.3ms
image 2/1280 C:\Users\dawoo\desktop\sf7\coding\pytorch\multi_scratch\test\images\204_101_10_004dd549-d0fa-46da-8d98-8c972db04466.jpg: 320x640 (no detections), 11.0ms
image 3/1280 C:\Users\dawoo\desktop\sf7\coding\pytorch\multi_scratch\test\images\204_101_10_02768548-17b9-43b1-b92f-b24bc20a30

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, roc_curve, roc_auc_score
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

pred = []
test_test_20 = pd.concat([ok_test_data, fault_test_data], ignore_index=True)

# 결과 생성
for result in results:
    if len(result.boxes) > 0:  # Detection이 있을 경우
        # 각 box에서 confidence가 가장 높은 클래스 선택
        pred.append(int(result.boxes[0].cls))
    else:
        pred.append(0)  # No Detection은 '0'으로 처리

# y_test 생성
y_test = []

for i in range(len(test_test_20)):
    if test_test_20.iloc[i, 1] == 1:
        y_test.append(0)  # 정상
    elif test_test_20.iloc[i, 1] == 0:  # 파손
        if test_test_20.iloc[i, 2] == '범퍼':
            y_test.append(1)
        elif test_test_20.iloc[i, 2] == '도어':
            y_test.append(1)
        elif test_test_20.iloc[i, 2] == '휀더':
            y_test.append(1)
        elif test_test_20.iloc[i, 2] == '프레임':
            y_test.append(1)

# data evaluation

# 길이 확인
print(f"Length of y_test: {len(y_test)}")
print(f"Length of pred: {len(pred)}")

# 혼동 행렬
confmat = confusion_matrix(y_true=y_test, y_pred=pred)
print('혼동 행렬: ', confmat, sep='\n')

# 정확도
accuracy = accuracy_score(y_true=y_test, y_pred=pred)
print('정확도:', accuracy)

# 정밀도(precision)
precision = precision_score(y_true=y_test, y_pred=pred, average='macro')
print('정밀도: ', precision)

# 재현율(recall)
recall = recall_score(y_true=y_test, y_pred=pred, average='macro')
print('재현율: ', recall)


Length of y_test: 1280
Length of pred: 1280
혼동 행렬: 
[[348  37 255]
 [318 312  10]
 [  0   0   0]]
정확도: 0.515625
정밀도:  0.47216844351514836
재현율:  0.34375


c:\Users\dawoo\Desktop\SF7\coding\PYTORCH\pytorch-env\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [18]:
print(test_test_20)

                                                   path  quality part  \
0     D:\data\sources\bumper\scratch\205_101_10_3841...        1   범퍼   
1     D:\data\sources\bumper\scratch\205_101_10_8dcc...        1   범퍼   
2     D:\data\sources\bumper\scratch\205_101_10_4c8d...        1   범퍼   
3     D:\data\sources\bumper\scratch\205_101_10_981d...        1   범퍼   
4     D:\data\sources\bumper\scratch\205_101_10_9865...        1   범퍼   
...                                                 ...      ...  ...   
1275  D:\data\sources\door\scratch\204_101_20_7f6e3d...        0   도어   
1276  D:\data\sources\door\scratch\204_101_20_44ce84...        0   도어   
1277  D:\data\sources\door\scratch\204_101_20_f8236e...        0   도어   
1278  D:\data\sources\door\scratch\204_101_20_d3eaae...        0   도어   
1279  D:\data\sources\door\scratch\204_101_20_2ad16c...        0   도어   

                                                 bboxes  weight  
0                                                    []  

In [20]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

test_test_20 = pd.concat([test_bumper_ok, test_bumper_fault,
                         test_door_scratch_ok, test_door_scratch_fault], ignore_index=True)
# 결과 생성
pred_binary = []  # 이진 분류 예측값
for result in results:
    if len(result.boxes) > 0:  # Detection이 있을 경우
        # '정상'과 '파손'으로 단순화
        pred_binary.append(1)  # 파손
    else:
        pred_binary.append(0)  # 정상

# y_test 생성
y_test_binary = []  # 이진 분류 실제값
for i in range(len(test_test_20)):
    if test_test_20.iloc[i, 1] == 1:  # 정상
        y_test_binary.append(0)
    elif test_test_20.iloc[i, 1] == 0:  # 파손
        y_test_binary.append(1)

# 데이터 평가
# 길이 확인
print(f"Length of y_test_binary: {len(y_test_binary)}")
print(f"Length of pred_binary: {len(pred_binary)}")

# 혼동 행렬
confmat_binary = confusion_matrix(y_true=y_test_binary, y_pred=pred_binary)
print('혼동 행렬 (2x2):', confmat_binary, sep='\n')

# 정확도
accuracy = accuracy_score(y_true=y_test_binary, y_pred=pred_binary)
print('정확도:', accuracy)

# 정밀도(precision)
precision = precision_score(y_true=y_test_binary, y_pred=pred_binary)
print('정밀도: ', precision)

# 재현율(recall)
recall = recall_score(y_true=y_test_binary, y_pred=pred_binary)
print('재현율: ', recall)


Length of y_test_binary: 1280
Length of pred_binary: 1280
혼동 행렬 (2x2):
[[582  58]
 [ 24 616]]
정확도: 0.9359375
정밀도:  0.913946587537092
재현율:  0.9625


In [6]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

test_test_20 = pd.concat([test_bumper_ok, test_bumper_fault,
                         test_door_scratch_ok, test_door_scratch_fault], ignore_index=True)
# 결과 생성
pred_binary = []  # 이진 분류 예측값
for result in results:
    if len(result.boxes) > 0:  # Detection이 있을 경우
        # '정상'과 '파손'으로 단순화
        pred_binary.append(1)  # 파손
    else:
        pred_binary.append(0)  # 정상

# y_test 생성
y_test_binary = []  # 이진 분류 실제값
for i in range(len(test_test_20)):
    if test_test_20.iloc[i, 1] == 1:  # 정상
        y_test_binary.append(0)
    elif test_test_20.iloc[i, 1] == 0:  # 파손
        y_test_binary.append(1)

# 혼동 행렬 계산
conf_matrix = confusion_matrix(y_test_binary, pred_binary)

# 각 지표 계산
accuracy = accuracy_score(y_test_binary, pred_binary)
precision = precision_score(y_test_binary, pred_binary)
recall = recall_score(y_test_binary, pred_binary)
f1 = f1_score(y_test_binary, pred_binary)

# 결과 출력
print("혼동 행렬 (2x2):")
print(conf_matrix)
print(f"정확도: {accuracy:.4f}")
print(f"정밀도: {precision:.4f}")
print(f"재현율: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

혼동 행렬 (2x2):
[[594  46]
 [ 72 568]]
정확도: 0.9078
정밀도: 0.9251
재현율: 0.8875
F1-Score: 0.9059


In [22]:
from sklearn.metrics import precision_score, recall_score

# zero_division 설정 추가
precision = precision_score(y_true=y_test, y_pred=pred, average='macro', zero_division=1)
recall = recall_score(y_true=y_test, y_pred=pred, average='macro', zero_division=1)

# 출력
print(f"정밀도: {precision}")
print(f"재현율: {recall}")

# 혼동 행렬 출력
confmat = confusion_matrix(y_true=y_test, y_pred=pred)
print('혼동 행렬: ', confmat, sep='\n')


정밀도: 0.43313492063492065
재현율: 0.5145833333333334
혼동 행렬: 
[[178   1   0  16   0   3  42   0]
 [ 21  18   0   0   0   0   9   0]
 [ 58   1   0   1   0   1   8  27]
 [ 40   0   0   0   0   0   6   2]
 [ 18   0   0   0   0   1  29   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]


In [15]:
print(f"Length of y_test: {len(y_test)}")
print(f"Length of pred: {len(pred)}")

print(f"Length of test_test_20: {len(test_test_20)}")
print(f"Length of results: {len(results)}")


Length of y_test: 240
Length of pred: 480
Length of test_test_20: 480
Length of results: 480


In [1]:
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

# 학습된 모델 경로
model = YOLO("model_8_s_80_12_1920_test8.pt")  # 예: 'model_8_m_100_8_640.pt'

# 이미지 파일 경로
image_path = "C:\\Users\\dawoo\\Desktop\\범퍼1.jpg"

# 이미지를 불러와서 예측
result = model(image_path)

# 예측 결과 출력
result[0].show()  # 첫 번째 예측 결과의 바운딩 박스를 이미지로 출력

# 예측된 객체들의 정보 출력
boxes = result[0].boxes.xywh  # 바운딩 박스 정보 (x_center, y_center, width, height)
print(f"boxes : {boxes}")  # 예측된 바운딩 박스 정보 출력

# 만약 이미지 저장을 원한다면:
result[0].save("C:\\Users\\dawoo\\Desktop\\predict.jpg")  # 예측된 이미지를 저장



image 1/1 C:\Users\dawoo\Desktop\1.jpg: 448x640 (no detections), 72.1ms
Speed: 8.0ms preprocess, 72.1ms inference, 79.0ms postprocess per image at shape (1, 3, 448, 640)
boxes : tensor([], device='cuda:0', size=(0, 4))


'C:\\Users\\dawoo\\Desktop\\predict.jpg'

In [ ]:
print("results 길이:", len(results))
print("test_test_20 길이:", len(test_test_20))


In [2]:
import cv2
from ultralytics import YOLO

# YOLOv8 모델 로드
model_path = "model_8_s_80_12_1920_test8.pt"  # 학습한 모델 경로
model = YOLO(model_path)
model.to("cuda")

# 카메라 열기
cap = cv2.VideoCapture(0)  # 기본 카메라 (ID 0)
if not cap.isOpened():
    print("카메라를 열 수 없습니다.")
    exit()

# 카메라 프레임 크기 설정 (선택 사항)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

# 색상 설정 (바운딩 박스와 텍스트)
box_color = (0, 255, 0)  # 녹색
text_color = (255, 255, 255)  # 흰색

print("Press 'q' to exit...")

while True:
    # 프레임 읽기
    ret, frame = cap.read()
    if not ret:
        print("프레임을 읽을 수 없습니다.")
        break
    flip_frame = cv2.flip(frame, 1)
    # 모델 추론 (YOLOv8)
    results = model.predict(source=frame, conf=0.5, show=False,
                    verbose=False)  # 이미지에 대해 추론
    detections = results[0]  # 첫 번째 결과 가져오기

    # 바운딩 박스와 라벨 그리기
    for box in detections.boxes:
        # 바운딩 박스 좌표 (정규화된 값 아님)
        x1, y1, x2, y2 = map(int, box.xyxy[0])  # 좌상단(x1, y1), 우하단(x2, y2)
        conf = box.conf[0]  # 신뢰도
        cls = int(box.cls[0])  # 클래스 ID
        label = f"{model.names[cls]} {conf:.2f}"  # 클래스 이름과 신뢰도

        # 바운딩 박스와 라벨 추가
        cv2.rectangle(frame, (x1, y1), (x2, y2), box_color, 2)  # 바운딩 박스
        cv2.putText(frame, label, (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, text_color, 2)

    # 프레임 화면에 표시
    cv2.imshow("YOLOv8 Real-Time Detection", frame)

    # 'q' 키를 누르면 종료
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 자원 해제
cap.release()
cv2.destroyAllWindows()

Press 'q' to exit...


In [37]:
import cv2
from ultralytics import YOLO

# 모델 경로 설정
model_path_1 = "model_8_s_35_12_512.pt"  # 첫 번째 모델 경로
model_path_2 = "model_8_s_50_12_576_classchange.pt"  # 두 번째 모델 경로

# 두 모델 로드
model_1 = YOLO(model_path_1).to("cuda")
model_2 = YOLO(model_path_2).to("cuda")

# 카메라 열기
cap = cv2.VideoCapture(1)
if not cap.isOpened():
    print("카메라를 열 수 없습니다.")
    exit()

# 카메라 프레임 크기 설정
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

# 색상 설정
box_color = (0, 255, 0)
text_color = (255, 255, 255)

print("Press 'q' to exit...")

while True:
    # 프레임 읽기
    ret, frame = cap.read()
    if not ret:
        print("프레임을 읽을 수 없습니다.")
        break
    flip_frame = cv2.flip(frame, 1)

    # 첫 번째 모델 추론
    results_1 = model_1.predict(source=frame, conf=0.5, show=False, verbose=False)
    detections_1 = results_1[0]

    # 두 번째 모델 추론
    results_2 = model_2.predict(source=frame, conf=0.5, show=False, verbose=False)
    detections_2 = results_2[0]

    # 첫 번째 모델 바운딩 박스 그리기
    for box in detections_1.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        conf = box.conf[0]
        cls = int(box.cls[0])
        label = f"{model_1.names[cls]} {conf:.2f}"
        cv2.rectangle(frame, (x1, y1), (x2, y2), box_color, 2)
        cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, text_color, 2)

    # 두 번째 모델 바운딩 박스 그리기
    for box in detections_2.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        conf = box.conf[0]
        cls = int(box.cls[0])
        label = f"{model_2.names[cls]} {conf:.2f}"
        cv2.rectangle(frame, (x1, y1), (x2, y2), box_color, 2)
        cv2.putText(frame, label, (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, text_color, 2)

    # 화면에 프레임 표시
    cv2.imshow("YOLOv8 Real-Time Detection", frame)

    # 'q' 키를 누르면 종료
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# 자원 해제
cap.release()
cv2.destroyAllWindows()


Press 'q' to exit...


## 손실 그래프

In [ ]:
# loss function
import matplotlib.pyplot as plt

# 손실 감소 그래프
plt.subplot(1, 2, 1)
plt.plot(losses)
plt.grid()
plt.title('Loss over Epochs')
plt.xlabel('epoch')
plt.ylabel('Loss')