# 01. Tensor

In [5]:
# import torch
# torch.__version__

## 01. Tensor 초기화

In [4]:
import torch
import numpy as np

### 1-1. 초기화 되지 않은 Tensor
- 특정한 값이 채워지지 않은 상태로 생성하는 것

In [7]:
tensor = torch.empty(4, 2)
print(tensor)

tensor([[-7.1552e-07,  9.4448e-43],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])


### 1-2. 상수로 초기화된 Tensor
- 'torch.zeros()'
- 'torch.ones()'

In [10]:
a = torch.ones(3, 4)
a
b = torch.zeros(3, 4)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
a = torch.ones(3, 4, dtype=torch.long) # dtype = 데이터 타입 지정 가능
print(a)
b = torch.zeros(3, 4)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 1-3. 무작위로 초기화된 Tensor
- 'torch.rand()' : 0~1 사이의 값으로 무작위로 초기화
- 'torch.randn()' : 표준정규분포에서 무작위로 초기화

In [15]:
a = torch.rand(3, 3)
b = torch.randn(3, 3)
print(a)
print(b)

tensor([[0.0837, 0.6650, 0.8549],
        [0.5437, 0.8384, 0.8430],
        [0.5042, 0.3846, 0.7660]])
tensor([[ 0.1907,  0.0520,  0.4433],
        [ 0.1152, -0.9676,  0.5484],
        [-0.1215, -1.1339, -0.0158]])


### 1-4. 직접 입력한 값으로 초기화된 Tensor
- 'torch.tensor()' : 직접 입력한 값으로 초기화

In [16]:
a = torch.tensor([1, 2.3])
print(a)

tensor([1.0000, 2.3000])


### 1-5. Numpy 배열로부터 초기화

In [22]:
nd_arr = np.array([1, 2, 3])
nd_arr

a = torch.from_numpy(nd_arr)
a

# numpy array로 변환환
b = torch.tensor([1, 2.3])
new_nd = b.numpy()
type(new_nd)

numpy.ndarray

### 1-6. 특정 Tensor와 같은 타입, 무작위로 값을 채움

In [29]:
a = torch.ones(3, 4, dtype=torch.long)  # dtype = 데이터 타입 지정 가능
a

b = torch.rand_like(a, dtype=torch.float)
b

c = torch.randn_like(a, dtype=torch.float)
c

d = torch.zeros_like(a, dtype=torch.float)
d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 1-7. 

In [30]:
nd_arr = np.array([1, 2, 3])
nd_arr

a = torch.from_numpy(nd_arr)
a

# numpy array로 변환환
b = torch.tensor([1, 2, 3, 4, 5])
new_nd = b.numpy()

new_nd[2] = 100
print(new_nd)
print(b)

[  1   2 100   4   5]
tensor([  1,   2, 100,   4,   5])
