# 02. Tensor의 연산


In [1]:
import torch

### 2-1. 산술 연산


In [4]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor+2
print(tensor)

tensor([[0.0310, 0.0469],
        [0.2708, 0.7525]])
tensor([[2.0310, 2.0469],
        [2.2708, 2.7525]])


In [5]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor-2
print(tensor)

tensor([[0.0640, 0.5895],
        [0.5613, 0.9822]])
tensor([[-1.9360, -1.4105],
        [-1.4387, -1.0178]])


In [3]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor*2
print(tensor)

tensor([[0.1339, 0.7609],
        [0.6478, 0.0612]])
tensor([[0.2678, 1.5218],
        [1.2956, 0.1224]])


In [6]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor/2
print(tensor)

tensor([[0.6507, 0.6296],
        [0.9305, 0.9637]])
tensor([[0.3253, 0.3148],
        [0.4652, 0.4818]])


In [16]:
# 더하기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}\n")
print(x+y)

add = torch.add(x, y)
print(f"add :\n{add}")

# in-place 바꿔치기 연산
y.add_(x)
print(f"y :\n{y}")

x :
tensor([[0.6995, 0.1723],
        [0.6101, 0.8677]])
y :
tensor([[0.6400, 0.3139],
        [0.9852, 0.3318]])

tensor([[1.3395, 0.4862],
        [1.5953, 1.1995]])
add :
tensor([[1.3395, 0.4862],
        [1.5953, 1.1995]])
y :
tensor([[1.3395, 0.4862],
        [1.5953, 1.1995]])


In [25]:
# 빼기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}\n")
print(x-y)

sub = torch.sub(x, y)
print(f"sub :\n{sub}")

# in-place 바꿔치기 연산
y.sub_(x)
print(f"y :\n{y}")

x :
tensor([[0.5803, 0.5546],
        [0.3818, 0.8436]])
y :
tensor([[0.0163, 0.1559],
        [0.7486, 0.7251]])

tensor([[ 0.5640,  0.3987],
        [-0.3669,  0.1184]])
sub :
tensor([[ 0.5640,  0.3987],
        [-0.3669,  0.1184]])
y :
tensor([[-0.5640, -0.3987],
        [ 0.3669, -0.1184]])


In [23]:
# 곱하기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}\n")
print(x*y)

mul = torch.mul(x, y)
print(f"mul :\n{mul}")

# in-place 바꿔치기 연산
y.mul_(x)
print(f"y :\n{y}")

x :
tensor([[0.6097, 0.8994],
        [0.4748, 0.2445]])
y :
tensor([[0.2689, 0.8959],
        [0.0156, 0.7405]])

tensor([[0.1639, 0.8058],
        [0.0074, 0.1810]])
mul :
tensor([[0.1639, 0.8058],
        [0.0074, 0.1810]])
y :
tensor([[0.1639, 0.8058],
        [0.0074, 0.1810]])


In [24]:
# 나누기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}\n")
print(x/y)

div = torch.div(x, y)
print(f"div :\n{div}")

# in-place 바꿔치기 연산
y.div_(x)
print(f"y :\n{y}")

x :
tensor([[0.3811, 0.6899],
        [0.6426, 0.2721]])
y :
tensor([[0.4205, 0.7194],
        [0.1331, 0.5230]])

tensor([[0.9065, 0.9589],
        [4.8260, 0.5203]])
div :
tensor([[0.9065, 0.9589],
        [4.8260, 0.5203]])
y :
tensor([[1.1032, 1.0428],
        [0.2072, 1.9219]])
