In [1]:
import torch

# -------------------------------------------------------------------------------

In [5]:
tensor = torch.rand(2, 2)
print(tensor)

tensor+=2
print(tensor)

tensor([[0.5787, 0.9168],
        [0.6871, 0.4201]])
tensor([[2.5787, 2.9168],
        [2.6871, 2.4201]])


In [6]:
tensor = torch.rand(2, 2)
print(tensor)

tensor-=2
print(tensor)

tensor([[0.4908, 0.3743],
        [0.8701, 0.8905]])
tensor([[-1.5092, -1.6257],
        [-1.1299, -1.1095]])


In [7]:
tensor = torch.rand(2, 2)
print(tensor)

tensor*=2
print(tensor)

tensor([[0.2476, 0.5306],
        [0.1458, 0.2720]])
tensor([[0.4951, 1.0611],
        [0.2917, 0.5440]])


In [8]:
tensor = torch.rand(2, 2)
print(tensor)

tensor/=2
print(tensor)

tensor([[0.0864, 0.5185],
        [0.4497, 0.4662]])
tensor([[0.0432, 0.2593],
        [0.2249, 0.2331]])


# -------------------------------------------------------------------------------

In [15]:
# 더하기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}")
print(f"x + y =\n{x+y}")

add = torch.add(x, y)
print(f"add :\n{add}")

y.add_(x)
print(f"\n{y}")

x :
tensor([[0.8356, 0.1841],
        [0.8445, 0.2060]])
y :
tensor([[0.1822, 0.7274],
        [0.7887, 0.6342]])
x + y =
tensor([[1.0178, 0.9115],
        [1.6332, 0.8402]])
add :
tensor([[1.0178, 0.9115],
        [1.6332, 0.8402]])

tensor([[1.0178, 0.9115],
        [1.6332, 0.8402]])


In [24]:
# 빼기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}")
print(f"x - y =\n{x-y}")

sub = torch.sub(x, y)
print(f"sub :\n{sub}")

y.sub_(x)
print(f"y.sub_ :\n{y}")

# x.sub_(y)
# print(f"x.sub_ :\n{x}")

x :
tensor([[0.1956, 0.6753],
        [0.6222, 0.3770]])
y :
tensor([[0.2175, 0.1519],
        [0.6051, 0.7657]])
x - y =
tensor([[-0.0219,  0.5234],
        [ 0.0170, -0.3888]])
sub :
tensor([[-0.0219,  0.5234],
        [ 0.0170, -0.3888]])
y.sub_ :
tensor([[ 0.0219, -0.5234],
        [-0.0170,  0.3888]])


In [27]:
# 곱하기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}")
print(f"x * y =\n{x*y}")

mul = torch.mul(x, y)
print(f"mul :\n{mul}")

y.mul_(x)
print(f"y.mul_ :\n{y}")

# x.sub_(y)
# print(f"x.sub_ :\n{x}")

x :
tensor([[0.3289, 0.9181],
        [0.8280, 0.5237]])
y :
tensor([[0.4391, 0.7865],
        [0.9444, 0.4778]])
x * y =
tensor([[0.1444, 0.7221],
        [0.7820, 0.2502]])
mul :
tensor([[0.1444, 0.7221],
        [0.7820, 0.2502]])
y.mul_ :
tensor([[0.1444, 0.7221],
        [0.7820, 0.2502]])


In [29]:
# 나누기
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{x}\ny :\n{y}")
print(f"x / y =\n{x/y}")

div = torch.div(x, y)
print(f"div :\n{div}")

# y.div_(x)
# print(f"y.div_ :\n{y}")

x.div_(y)
print(f"x.div_ :\n{x}")

x :
tensor([[0.4754, 0.8434],
        [0.0490, 0.2005]])
y :
tensor([[0.6772, 0.3855],
        [0.9569, 0.4388]])
x / y =
tensor([[0.7020, 2.1880],
        [0.0512, 0.4569]])
div :
tensor([[0.7020, 2.1880],
        [0.0512, 0.4569]])
x.div_ :
tensor([[0.7020, 2.1880],
        [0.0512, 0.4569]])
