In [1]:
import torch
import numpy as np

## PyTorch Quiz 1 : Tensor 초기화

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [5]:
# 여기에 코드를 작성합니다
a = torch.empty(3, 4, dtype=torch.int)
a

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [4]:
# 여기에 코드를 작성합니다
a = torch.zeros(2, 5, 3, dtype=torch.int)
a

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)

### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [6]:
# 여기에 코드를 작성합니다
a = torch.ones(4, 4, dtype=torch.int)
a

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [8]:
# 여기에 코드를 작성합니다
a = torch.rand(3, 3, dtype=torch.float64)
a

tensor([[0.7065, 0.9413, 0.5512],
        [0.9407, 0.5522, 0.0652],
        [0.8878, 0.3809, 0.4102]], dtype=torch.float64)

### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [14]:
# 여기에 코드를 작성합니다

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a

ndarr = np.array([[1, 2, 3], [4, 5, 6]])
tensor = torch.from_numpy(ndarr)
tensor
print(a)
print(tensor)

b = a.numpy()
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
[[1 2 3]
 [4 5 6]]


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요. 

In [17]:
# 여기에 코드를 작성합니다
a = torch.randn(2, 2, dtype=torch.float32)
a
b = torch.zeros_like(a, dtype=torch.int)
b

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)