In [1]:
import torch
import numpy as np

In [7]:
a = torch.empty(4, 2, dtype=torch.int)
a

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [6]:
a = torch.zeros(4, 2, dtype=torch.int)
a

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [8]:
a = torch.ones(4, 2, dtype=torch.int)
a

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)

In [9]:
a = torch.rand(4, 2)
a

tensor([[0.1487, 0.3437],
        [0.9228, 0.6120],
        [0.8942, 0.5539],
        [0.5558, 0.4020]])

In [12]:
a = torch.tensor([1, 2.3], dtype=torch.int)
a

tensor([1, 2], dtype=torch.int32)

In [15]:
ndarr = np.array([1, 2, 3])
ndarr

a = torch.from_numpy(ndarr)
a

a = torch.tensor([1, 2, 3])
b = a.numpy()
b

array([1, 2, 3], dtype=int64)

In [25]:
a = torch.ones(3, 4, dtype=torch.long)
a
b = torch.rand_like(a, dtype=torch.float)
b
c = torch.randn_like(a, dtype=torch.float)
c
d = torch.zeros_like(a)
d

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [31]:
ndarr = np.array([1, 2, 3])
ndarr

a = torch.from_numpy(ndarr)
a

b = torch.tensor([1, 2, 3, 4, 5])
new_ndarr = b.numpy()
new_ndarr

new_ndarr[2] = 100
print(f"new_ndarr : {new_ndarr}")
print(f"b : {b}")


new_ndarr : [  1   2 100   4   5]
b : tensor([  1,   2, 100,   4,   5])
