## PyTorch Quiz 1 : Tensor 초기화

In [2]:
import numpy as np
import torch

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [14]:
# 여기에 코드를 작성합니다

a=torch.empty(3,4)
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [6]:
# 여기에 코드를 작성합니다

a=torch.zeros(2,5,3,dtype=torch.float64)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [5]:
# 여기에 코드를 작성합니다

a = torch.ones(4, 4, dtype=torch.int)
a

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [4]:
# 여기에 코드를 작성합니다

a = torch.rand(3, 3)
a

tensor([[0.1655, 0.0632, 0.6055],
        [0.9475, 0.3765, 0.9815],
        [0.7165, 0.5036, 0.0081]])

### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [24]:
# 여기에 코드를 작성합니다
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
c = torch.from_numpy(b)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 값을 모두 0으로 바꿔보세요. 

In [3]:
# 여기에 코드를 작성합니다

a = torch.randn(2, 2)
print(a)

b = torch.zeros_like(a)
print(b)

tensor([[0.2097, 0.7969],
        [0.6688, 2.4887]])
tensor([[0., 0.],
        [0., 0.]])


### 1-7. Tensor의 속성

In [14]:
tensor = torch.rand(3, 4, dtype=torch.float64)
print(tensor.size())  # 사이즈
print(tensor.shape)  # 사이즈
print(tensor.dtype)  # 데이터 타입
print(tensor.device)  # 디바이스

torch.Size([3, 4])
torch.Size([3, 4])
torch.float64
cpu


In [12]:
if torch.cuda.is_available():
    print(True)

True


### 1-8. 특정 타입의 Tensor 생성

In [17]:
tensor = torch.rand(3, 4, dtype=torch.float64)
tensor.dtype

float_tensor = torch.FloatTensor([1, 2, 3])
float_tensor.dtype

int_tensor = torch.IntTensor([1.1, 2.3, 3.4])
print(int_tensor)
print(int_tensor.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


### 1-9. 데이터 타입 캐스팅

In [19]:
tensor = torch.rand(3, 4, dtype=torch.float64)

float_tensor = torch.FloatTensor([1, 2, 3])
print(float_tensor.int())

int_tensor = torch.IntTensor([1.1, 2.3, 3.4])
print(int_tensor.float())

tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10. CUDA Tensor

In [20]:
print(torch.cuda.is_available())

True


In [21]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor = torch.rand(3, 4, dtype=torch.float64)

tensor = tensor.to(device)

tensor.device

device(type='cuda', index=0)

### 1-11. 다차원 Tensor 표현

#### 1-11-1. 0D Tensor(Scalar)

In [26]:
t3 = torch.tensor(100)

print(t3.ndim)
print(t3.shape)
print(t3)

0
torch.Size([])
tensor(100)


#### 1-11-2 1D Tensor(Vector)
- 값들을 저장하고 있는 리스트와 유사한 Tensor

In [27]:
t3 = torch.tensor([1, 2, 3])

print(t3.ndim)
print(t3.shape)
print(t3)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-3 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두개의 축이 존재

In [28]:
t3 = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(t3.ndim)
print(t3.shape)
print(t3)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


#### 1-11-4 3D Tensor(Cube)
- 큐브와 같은 형태로 3개의 축이 존재

In [34]:
t3 = torch.tensor([[[1, 2, 3], [4, 5, 6]],
                   [[1, 2, 3], [4, 5, 6]]])

print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [32]:
t3 = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


#### 1-11-4. 4D Tensor
- 4개의 축이 존재

In [38]:
t4 = torch.rand(3, 2, 4, 5)
print(t4)

tensor([[[[0.3956, 0.9364, 0.0946, 0.7341, 0.2336],
          [0.5812, 0.4204, 0.9941, 0.4726, 0.5694],
          [0.2610, 0.5769, 0.4727, 0.7957, 0.5896],
          [0.9251, 0.6496, 0.7205, 0.2414, 0.7628]],

         [[0.3958, 0.6414, 0.8556, 0.4961, 0.2267],
          [0.2252, 0.3275, 0.5289, 0.2609, 0.6970],
          [0.1893, 0.6915, 0.6690, 0.3661, 0.4619],
          [0.6784, 0.6529, 0.4366, 0.7756, 0.6155]]],


        [[[0.6532, 0.2973, 0.1673, 0.0853, 0.5214],
          [0.6241, 0.0572, 0.8029, 0.2002, 0.9484],
          [0.3610, 0.7924, 0.4686, 0.7994, 0.4704],
          [0.5821, 0.4833, 0.6011, 0.7135, 0.1336]],

         [[0.7122, 0.9147, 0.0515, 0.9470, 0.3258],
          [0.6525, 0.8333, 0.9412, 0.3736, 0.7209],
          [0.5502, 0.9020, 0.8846, 0.1420, 0.6623],
          [0.3804, 0.2148, 0.2810, 0.7624, 0.1671]]],


        [[[0.2879, 0.0623, 0.5420, 0.9552, 0.4825],
          [0.8677, 0.4388, 0.4057, 0.4726, 0.7609],
          [0.5937, 0.5874, 0.5845, 0.0033, 0.2844],
