# 02. Tensor의 연산


In [1]:
import torch

### 2-1. 산술 연산


In [4]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor+2
print(tensor)

tensor([[0.0310, 0.0469],
        [0.2708, 0.7525]])
tensor([[2.0310, 2.0469],
        [2.2708, 2.7525]])


In [5]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor-2
print(tensor)

tensor([[0.0640, 0.5895],
        [0.5613, 0.9822]])
tensor([[-1.9360, -1.4105],
        [-1.4387, -1.0178]])


In [3]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor*2
print(tensor)

tensor([[0.1339, 0.7609],
        [0.6478, 0.0612]])
tensor([[0.2678, 1.5218],
        [1.2956, 0.1224]])


In [6]:
tensor = torch.rand(2, 2)
print(tensor)
tensor = tensor/2
print(tensor)

tensor([[0.6507, 0.6296],
        [0.9305, 0.9637]])
tensor([[0.3253, 0.3148],
        [0.4652, 0.4818]])


In [16]:
# 더하기
y = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{y}\ny :\n{y}\n")
print(y+y)

add = torch.add(y, y)
print(f"add :\n{add}")

# in-place 바꿔치기 연산
y.add_(y)
print(f"y :\n{y}")

x :
tensor([[0.6995, 0.1723],
        [0.6101, 0.8677]])
y :
tensor([[0.6400, 0.3139],
        [0.9852, 0.3318]])

tensor([[1.3395, 0.4862],
        [1.5953, 1.1995]])
add :
tensor([[1.3395, 0.4862],
        [1.5953, 1.1995]])
y :
tensor([[1.3395, 0.4862],
        [1.5953, 1.1995]])


In [25]:
# 빼기
y = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{y}\ny :\n{y}\n")
print(y-y)

sub = torch.sub(y, y)
print(f"sub :\n{sub}")

# in-place 바꿔치기 연산
y.sub_(y)
print(f"y :\n{y}")

x :
tensor([[0.5803, 0.5546],
        [0.3818, 0.8436]])
y :
tensor([[0.0163, 0.1559],
        [0.7486, 0.7251]])

tensor([[ 0.5640,  0.3987],
        [-0.3669,  0.1184]])
sub :
tensor([[ 0.5640,  0.3987],
        [-0.3669,  0.1184]])
y :
tensor([[-0.5640, -0.3987],
        [ 0.3669, -0.1184]])


In [23]:
# 곱하기
y = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{y}\ny :\n{y}\n")
print(y*y)

mul = torch.mul(y, y)
print(f"mul :\n{mul}")

# in-place 바꿔치기 연산
y.mul_(y)
print(f"y :\n{y}")

x :
tensor([[0.6097, 0.8994],
        [0.4748, 0.2445]])
y :
tensor([[0.2689, 0.8959],
        [0.0156, 0.7405]])

tensor([[0.1639, 0.8058],
        [0.0074, 0.1810]])
mul :
tensor([[0.1639, 0.8058],
        [0.0074, 0.1810]])
y :
tensor([[0.1639, 0.8058],
        [0.0074, 0.1810]])


In [24]:
# 나누기
y = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x :\n{y}\ny :\n{y}\n")
print(y/y)

div = torch.div(y, y)
print(f"div :\n{div}")

# in-place 바꿔치기 연산
y.div_(y)
print(f"y :\n{y}")

x :
tensor([[0.3811, 0.6899],
        [0.6426, 0.2721]])
y :
tensor([[0.4205, 0.7194],
        [0.1331, 0.5230]])

tensor([[0.9065, 0.9589],
        [4.8260, 0.5203]])
div :
tensor([[0.9065, 0.9589],
        [4.8260, 0.5203]])
y :
tensor([[1.1032, 1.0428],
        [0.2072, 1.9219]])


## 2-2. 각종 연산


In [7]:
a = torch.tensor(-10)
print(f"절대값 : {torch.abs(a)}")

b = torch.tensor(3.3)
print(f"올림 : {torch.ceil(b)}")
print(f"반올림 : {torch.round(b)}")
print(f"내림 : {torch.floor(b)}")

절대값 : 10
올림 : 4.0
반올림 : 3.0
내림 : 3.0


In [15]:
c = torch.randn(2, 2)
print(f"클램프 :\n{torch.clamp(c, -0.5, 0.5)}")
d = torch.tensor([[0.8, 0.3], [-0.9, 0.4]])
print(f"클램프 :\n{torch.clamp(d, -0.5, 0.5)}")

클램프 :
tensor([[-0.3059,  0.5000],
        [ 0.5000, -0.5000]])
클램프 :
tensor([[ 0.5000,  0.3000],
        [-0.5000,  0.4000]])


In [16]:
y = torch.randn(2, 2)
print(f"최소값 :\n{torch.min(y)}")
print(f"최대값 :\n{torch.max(y)}")
print(f"평균 :\n{torch.mean(y)}")
print(f"표준편차 :\n{torch.std(y)}")
print(f"모든 원소의 합 :\n{torch.sum(y)}")
print(f"모든 원소의 합 :\n{torch.sum(y, dim=0)}")

최소값 :
-1.5781131982803345
최대값 :
1.8651868104934692
평균 :
0.13418352603912354
표준편차 :
1.5446454286575317
모든 원소의 합 :
0.5367341041564941
모든 원소의 합 :
tensor([0.2871, 0.2497])


In [31]:
y = torch.tensor([[1, 2], [3, 4]])
print(f"최소값 :\n{torch.min(y)}")
print(f"최대값 :\n{torch.max(y)}")
# print(f"평균 :\n{torch.mean(y)}")
# print(f"표준편차 :\n{torch.std(y)}")
print(f"모든 원소의 합 :\n{torch.sum(y)}")
print(f"모든 원소의 합 :\n{torch.sum(y, dim=1)}")
print(f"모든 원소의 곲 :\n{torch.prod(y)}")
print(f"중복된 값 제거 :\n{torch.unique(torch.tensor(
    [1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]))}")

최소값 :
1
최대값 :
4
모든 원소의 합 :
10
모든 원소의 합 :
tensor([3, 7])
모든 원소의 곲 :
24
중복된 값 제거 :
tensor([1, 2, 3, 4])


## 2-3. 내적(dot product)


In [33]:
x = torch.tensor([[1, 2], 
                  [3, 4]])
y = torch.tensor([[5, 6], 
                  [7, 8]])

result = torch.matmul(x, y)
print(result)

tensor([[19, 22],
        [43, 50]])
