# 03. Tensor의 조작

In [2]:
import torch

## 3-1. 인덱싱, 슬라이싱
- Numpy처럼 활용


In [ ]:
tensor = torch.tensor([[1, 2], [3, 4]])

print(tensor[0, 1])
print(tensor[0, :])

a = torch.tensor([1, 2, 3, 4, 5])
print(a[-1])
print(a[-2:])

b = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
b.shape
c = b[b > 5]  # 조건부 인덱싱
print(c)

d = b[b % 2 == 0]
print(d)

b[[0, 1], [1, 2]]

## 3-2. Tensor의 크기, 모양 변경

In [ ]:
t = torch.rand(4, 5)
print(t)
x = t.view(5, 4)
print(x)

y = t.view(10, 2)
print(y)

z = t.view(-1, 10)
print(z)

## 3-3. Tensor의 숫자값 얻기

In [ ]:
x = torch.tensor(10)
print(x.item())

y = torch.rand(1)
print(y.item())

## 3-4. 차원 축소와 증가

#### 3-4-1. 차원 축소
- 'torch.squeeze()' : 크기가 1인 차원을 축소함


In [5]:
t = torch.rand(1, 3, 3)
print(f"t.shape : {t.shape}")
print(t)
ts = torch.squeeze(t)
print(ts.shape)
print(ts)

t.shape : torch.Size([1, 3, 3])
tensor([[[0.2559, 0.5392, 0.2874],
         [0.2778, 0.8211, 0.0074],
         [0.5680, 0.6934, 0.6692]]])
torch.Size([3, 3])
tensor([[0.2559, 0.5392, 0.2874],
        [0.2778, 0.8211, 0.0074],
        [0.5680, 0.6934, 0.6692]])


#### 3-4-2. 차원 증가
- 'torch.unsqueeze()' : 지정한 위치에 새로운 차원을 생성

In [13]:
t = torch.rand(3, 3, 3)
print(f"t.shape : {t.shape}")
print(t)

tus = torch.unsqueeze(t, 0)
print(tus)

t.shape : torch.Size([3, 3, 3])
tensor([[[0.7379, 0.9611, 0.6663],
         [0.2479, 0.1376, 0.2735],
         [0.3498, 0.0764, 0.1358]],

        [[0.2317, 0.0077, 0.3304],
         [0.1198, 0.9428, 0.9729],
         [0.1642, 0.8619, 0.7343]],

        [[0.8076, 0.5298, 0.4551],
         [0.0203, 0.9599, 0.2196],
         [0.1421, 0.4221, 0.3358]]])
tensor([[[[0.7379, 0.9611, 0.6663],
          [0.2479, 0.1376, 0.2735],
          [0.3498, 0.0764, 0.1358]],

         [[0.2317, 0.0077, 0.3304],
          [0.1198, 0.9428, 0.9729],
          [0.1642, 0.8619, 0.7343]],

         [[0.8076, 0.5298, 0.4551],
          [0.0203, 0.9599, 0.2196],
          [0.1421, 0.4221, 0.3358]]]])


## 3-5. Tensor간 결합

### - 'torch.stack()' : 동일한 형식의 Tensor를 새롭게 그룹화 함
### - 새로운 차원이 생성

In [15]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

z = torch.stack([x, y])
print(z)
print(z.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


### - 'torch.cat()' : 하나의 Tensor로 병합

### - 새로운 차원 생성 X

In [16]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

z = torch.cat((x, y), dim=0)
print(z)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [17]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8], [9, 10]])

z = torch.cat((x, y), dim=0)
print(z)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])


In [19]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

z = torch.cat((x, y), dim=1)
print(z)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


## 3-6. Tensor 나누기

### - 'torch.chunk()'
- 텐서를 몇 개로 나눌지 지정
- 나누어 떨어지지 않으면 마지막 조각은 조각은 크기가 다를 수 있음

In [23]:
t = torch.rand(3, 3)
print(t)

a, b, c = torch.chunk(t, 3, dim=0)
print(f"a :\n{a}\nb :\n{b},\nc :{c}")

tensor([[0.2515, 0.9756, 0.5231],
        [0.9797, 0.0529, 0.6935],
        [0.3180, 0.3169, 0.2865]])
a :
tensor([[0.2515, 0.9756, 0.5231]])
b :
tensor([[0.9797, 0.0529, 0.6935]]),
c :tensor([[0.3180, 0.3169, 0.2865]])


In [24]:
t = torch.rand(5, 3)
print(t)

a, b, c = torch.chunk(t, 3, dim=0)
print(f"a :\n{a}\nb :\n{b},\nc :{c}")

tensor([[0.0248, 0.2289, 0.2342],
        [0.2228, 0.6672, 0.4914],
        [0.5159, 0.6313, 0.1224],
        [0.5172, 0.1952, 0.5603],
        [0.7011, 0.0977, 0.0625]])
a :
tensor([[0.0248, 0.2289, 0.2342],
        [0.2228, 0.6672, 0.4914]])
b :
tensor([[0.5159, 0.6313, 0.1224],
        [0.5172, 0.1952, 0.5603]]),
c :tensor([[0.7011, 0.0977, 0.0625]])


In [26]:
t = torch.rand(5, 3)
print(t)

a, b = torch.chunk(t, 2, dim=0)
print(f"a :\n{a}\nb :\n{b}")

tensor([[0.2303, 0.8941, 0.6137],
        [0.7270, 0.3640, 0.9688],
        [0.1629, 0.9161, 0.3969],
        [0.1429, 0.1688, 0.1441],
        [0.4025, 0.6164, 0.9044]])
a :
tensor([[0.2303, 0.8941, 0.6137],
        [0.7270, 0.3640, 0.9688],
        [0.1629, 0.9161, 0.3969]])
b :
tensor([[0.1429, 0.1688, 0.1441],
        [0.4025, 0.6164, 0.9044]])


### - 'torch.split()'
- Tesnor의 크기를 기준으로 나눔

In [30]:
t = torch.rand(3, 6)
print(t)
x = torch.split(t, 3, dim=0)
print(x)

tensor([[0.3527, 0.4249, 0.4903, 0.2256, 0.2748, 0.5630],
        [0.8157, 0.3651, 0.3039, 0.6136, 0.5688, 0.6339],
        [0.2606, 0.0438, 0.0656, 0.7009, 0.5329, 0.3149]])
(tensor([[0.3527, 0.4249, 0.4903, 0.2256, 0.2748, 0.5630],
        [0.8157, 0.3651, 0.3039, 0.6136, 0.5688, 0.6339],
        [0.2606, 0.0438, 0.0656, 0.7009, 0.5329, 0.3149]]),)


In [31]:
t = torch.rand(3, 6)
print(t)
x = torch.split(t, 3, dim=1)
print(x)

tensor([[0.0644, 0.3199, 0.0881, 0.4632, 0.5018, 0.4877],
        [0.5758, 0.1284, 0.5718, 0.6688, 0.6758, 0.5355],
        [0.6162, 0.7179, 0.0133, 0.6919, 0.7251, 0.9741]])
(tensor([[0.0644, 0.3199, 0.0881],
        [0.5758, 0.1284, 0.5718],
        [0.6162, 0.7179, 0.0133]]), tensor([[0.4632, 0.5018, 0.4877],
        [0.6688, 0.6758, 0.5355],
        [0.6919, 0.7251, 0.9741]]))


In [35]:
t = torch.rand(6, 3)
print(t)
x, y = torch.split(t, 3, dim=0)
print(f"x :\n{x}\ny :\n{y}")

tensor([[0.4470, 0.9377, 0.5686],
        [0.7516, 0.8575, 0.7463],
        [0.4796, 0.6881, 0.8366],
        [0.9344, 0.5658, 0.2467],
        [0.6001, 0.6056, 0.5905],
        [0.3207, 0.6618, 0.8904]])
x :
tensor([[0.4470, 0.9377, 0.5686],
        [0.7516, 0.8575, 0.7463],
        [0.4796, 0.6881, 0.8366]])
y :
tensor([[0.9344, 0.5658, 0.2467],
        [0.6001, 0.6056, 0.5905],
        [0.3207, 0.6618, 0.8904]])


In [39]:
t = torch.tensor([1, 2, 3, 4, 5])
print(t)
x, y, z = torch.split(t, [2, 2, 1], dim=0)
print(f"x :\n{x}\ny :\n{y}\nz :\n{z}")

tensor([1, 2, 3, 4, 5])
x :
tensor([1, 2])
y :
tensor([3, 4])
z :
tensor([5])
