## PyTorch Quiz 2 : 연산


In [49]:
import torch

### 1. 덧셈과 뺄셈 연습

1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [50]:
# 여기에 코드를 작성합니다

a = torch.tensor([2, 4, 6])
print(f"a :\n{a}")
a += 5
print(f"a + 5 :\n{a}")
a -= 3
print(f"a - 3 :\n{a}")

a :
tensor([2, 4, 6])
a + 5 :
tensor([ 7,  9, 11])
a - 3 :
tensor([4, 6, 8])


### 2. Tensor 간의 연산

1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(\*), 나누세요(/).


In [51]:
# 여기에 코드를 작성합니다
a = torch.tensor([[0.1530, 0.2366, 0.4711],
                  [0.3323, 0.8252, 0.8589],
                  [0.3732, 0.8566, 0.8936]])
b = torch.tensor([[0.0634, 0.5723, 0.9058],
                  [0.1459, 0.9274, 0.6232],
                  [0.3685, 0.8091, 0.5346]])

print(f"x + y:\n{a+b}")
print(f"x - y:\n{a-b}")
print(f"x * y:\n{a*b}")
print(f"x / y:\n{a/b}")

x + y:
tensor([[0.2164, 0.8089, 1.3769],
        [0.4782, 1.7526, 1.4821],
        [0.7417, 1.6657, 1.4282]])
x - y:
tensor([[ 0.0896, -0.3357, -0.4347],
        [ 0.1864, -0.1022,  0.2357],
        [ 0.0047,  0.0475,  0.3590]])
x * y:
tensor([[0.0097, 0.1354, 0.4267],
        [0.0485, 0.7653, 0.5353],
        [0.1375, 0.6931, 0.4777]])
x / y:
tensor([[2.4132, 0.4134, 0.5201],
        [2.2776, 0.8898, 1.3782],
        [1.0128, 1.0587, 1.6715]])


In [52]:
# 여기에 코드를 작성합니다
c = torch.tensor([[0.1530, 0.2366, 0.4711],
                  [0.3323, 0.8252, 0.8589],
                  [0.3732, 0.8566, 0.8936]])
d = torch.tensor([[0.0634, 0.5723, 0.9058],
                  [0.1459, 0.9274, 0.6232],
                  [0.3685, 0.8091, 0.5346]])


add = torch.add(c, d)
sub = torch.sub(c, d)
mul = torch.mul(c, d)
div = torch.div(c, d)

print(f"add :\n{add}")
print(f"sub :\n{sub}")
print(f"mul :\n{mul}")
print(f"div :\n{div}")

add :
tensor([[0.2164, 0.8089, 1.3769],
        [0.4782, 1.7526, 1.4821],
        [0.7417, 1.6657, 1.4282]])
sub :
tensor([[ 0.0896, -0.3357, -0.4347],
        [ 0.1864, -0.1022,  0.2357],
        [ 0.0047,  0.0475,  0.3590]])
mul :
tensor([[0.0097, 0.1354, 0.4267],
        [0.0485, 0.7653, 0.5353],
        [0.1375, 0.6931, 0.4777]])
div :
tensor([[2.4132, 0.4134, 0.5201],
        [2.2776, 0.8898, 1.3782],
        [1.0128, 1.0587, 1.6715]])


In [53]:
# 여기에 코드를 작성합니다
e = torch.tensor([[0.1530, 0.2366, 0.4711],
                  [0.3323, 0.8252, 0.8589],
                  [0.3732, 0.8566, 0.8936]])
f = torch.tensor([[0.0634, 0.5723, 0.9058],
                  [0.1459, 0.9274, 0.6232],
                  [0.3685, 0.8091, 0.5346]])
e_coppied = e.clone()
print(f"e.add_(f) :\n{e_coppied.add_(f)}")
e_coppied = e.clone()
print(f"e.sub_(f) :\n{e_coppied.sub_(f)}")
e_coppied = e.clone()
print(f"e.mul_(f) :\n{e_coppied.mul_(f)}")
e_coppied = e.clone()
print(f"e.div_(f) :\n{e_coppied.div_(f)}")

e.add_(f) :
tensor([[0.2164, 0.8089, 1.3769],
        [0.4782, 1.7526, 1.4821],
        [0.7417, 1.6657, 1.4282]])
e.sub_(f) :
tensor([[ 0.0896, -0.3357, -0.4347],
        [ 0.1864, -0.1022,  0.2357],
        [ 0.0047,  0.0475,  0.3590]])
e.mul_(f) :
tensor([[0.0097, 0.1354, 0.4267],
        [0.0485, 0.7653, 0.5353],
        [0.1375, 0.6931, 0.4777]])
e.div_(f) :
tensor([[2.4132, 0.4134, 0.5201],
        [2.2776, 0.8898, 1.3782],
        [1.0128, 1.0587, 1.6715]])


### 3. 행렬의 내적 연산

1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:

- `[[1,2,3], [4,5,6]]`

2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:

- `[[7,8],[9,10],[11,12]]`

3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.


In [54]:
# 여기에 코드를 작성합니다

A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([[7, 8], [9, 10], [11, 12]])

result = torch.matmul(A, B)

print(f"result :\n{result}")

result :
tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한

1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.


In [61]:
# 여기에 코드를 작성합니다
# A = torch.tensor([[1, 2, 3], [4, 5, 6]])
# B = torch.tensor([[7, 8], [9, 10], [11, 12]])

R = torch.matmul(A, B)
R += 10

# result = torch.clamp(R, None, 100)
result = torch.clamp(R, None, max=100)
print(f"result :\n{result}")

result :
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산

#### 1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요

   ```
   [[1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]]
   ```

#### 2. 행렬 M의 각 열의 합계를 계산하세요.

- 행은 dim=1
- 열은 dim=0


In [64]:
# 여기에 코드를 작성합니다
M = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

# print(f"M :\n{M}")

result = torch.sum(M, dim=0)
print(f"result :\n{result}")

result :
tensor([55, 60, 65, 70, 75])
